import java.lang.Exception;
class Main{
  public static void main(String args[]) {
    try{
      No2941.main(args);
    }catch(Exception e){
      System.out.println();
      e.printStackTrace();
    }
    
  }
}